### PR TITLE
Create plot_genome_vs_cm.R

### PR DESCRIPTION
**Pull request by jeekinlau**
please check if my code works but it should produce this plot 
image

### CODE REVIEW

**Comment by jeekinlau** [comment]
function is ready to be merged

**Comment by Cristianetaniguti** [comment]
Issue #66

**Review by Cristianetaniguti — COMMENTED** [review]
* OneMap has the functions kosambi and haldane already, you can use them instead of the imf_h and imf_k
* Add a line to check if the input object is a list of sequences and provide an error if not

**Comment by jeekinlau** [comment]
fixed above mentions

**Review by Cristianetaniguti — APPROVED** [review]
Close issue #66

**Pull request merged**
